# Generated by Django 2.2.4 on 2019-08-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999999999)),
                ('token', models.CharField(max_length=999999999)),
                ('gold', models.FloatField()),
                ('encumbrance', models.FloatField()),
                ('visited', models.CharField(max_length=999999999)),
            ],
        ),
    ]
