# Generated by Django 2.2.4 on 2019-08-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='path',
            field=models.CharField(default='', max_length=999999999),
        ),
    ]
